version: "3.8"
services:
  app:
    build:
      context: .
      dockerfile: Dockerfile
    environment:
      ENV: ${ENV:-dev}
      STRATEGY: mrat_zscore
    env_file:
      - env/base.env
      - env/${ENV:-dev}.env
    volumes:
      - ./strategies:/app/strategies
      - ./env:/app/env
      - ./data:/app/data
    command: ["--files", "conf/{ENV}/${STRATEGY}.yml"]
